language: cpp
sudo: required
dist: trusty

branches:
  except:

compiler: 
  - gcc

install:
  - sudo apt-get --yes --force-yes install cmake wget unzip libboost-dev libboost-program-options-dev libboost-timer-dev libboost-filesystem-dev libboost-system-dev

before_script:
  - wget http://www.exiv2.org/exiv2-0.25.tar.gz
  - tar -xvf exiv2-0.25.tar.gz
  - cd exiv2-0.25/build
  - cmake ../
  - make -j4
  - sudo make install
  - cd ../..
  - wget https://github.com/Itseez/opencv/archive/3.0.0.zip
  - unzip 3.0.0.zip 
  - cd opencv-3.0.0
  - mkdir build
  - cd build
  - cmake -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_WITH_DEBUG_INFO=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF ..
  - make -j4
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ../src/
  - make -j4

script: cd examples && ./examples.sh


